// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueryableVsEnumerable;

namespace QueryableVsEnumerable.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20210628064709_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QueryableVsEnumerable.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5ec2305-3db5-4864-ba7d-bdc2c3da0d88"),
                            Date = new DateTime(2021, 6, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("80fd270c-de5f-4deb-90f9-ac76d28398a0"),
                            Date = new DateTime(2021, 5, 4, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("0469137b-ae56-40d3-9488-596a7a9e188d"),
                            Date = new DateTime(2021, 6, 21, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("6e63fd29-c5f9-4ec4-9f3f-57838454425b"),
                            Date = new DateTime(2021, 6, 18, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("b12b46ed-f1e8-4942-b525-87465d56084f"),
                            Date = new DateTime(2021, 5, 19, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("2bedf5b3-05a9-4d43-92db-0bbad201d1de"),
                            Date = new DateTime(2021, 6, 27, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("cbdafc5d-257f-4eec-8177-af56175bf26f"),
                            Date = new DateTime(2021, 5, 11, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
